// 7KC seed data. AU market: capsicum, coriander, snags, mince, Vegemite, Weet-Bix.
// All data is deterministic for demo purposes.

window.SEED = (() => {
  // --- Ingredients dictionary (subset, ~120 items, enough to feel real) ---
  const ING = [
    // produce (shelf_life short)
    ['banana', 'Bananas', 'produce', 5],
    ['apple', 'Apples', 'produce', 14],
    ['lemon', 'Lemons', 'produce', 21],
    ['lime', 'Limes', 'produce', 14],
    ['avocado', 'Avocados', 'produce', 4],
    ['tomato', 'Tomatoes', 'produce', 6],
    ['cherry_tomato', 'Cherry tomatoes', 'produce', 6],
    ['roma_tomato', 'Roma tomatoes', 'produce', 7],
    ['onion_brown', 'Brown onions', 'produce', 30],
    ['onion_red', 'Red onions', 'produce', 30],
    ['spring_onion', 'Spring onions', 'produce', 7],
    ['garlic', 'Garlic', 'produce', 30],
    ['ginger', 'Ginger', 'produce', 21],
    ['capsicum_red', 'Red capsicum', 'produce', 8],
    ['capsicum_green', 'Green capsicum', 'produce', 8],
    ['chilli', 'Red chilli', 'produce', 10],
    ['carrot', 'Carrots', 'produce', 21],
    ['potato', 'Potatoes', 'produce', 30],
    ['sweet_potato', 'Sweet potato', 'produce', 21],
    ['broccoli', 'Broccoli', 'produce', 7],
    ['cauliflower', 'Cauliflower', 'produce', 8],
    ['spinach', 'Baby spinach', 'produce', 5],
    ['rocket', 'Rocket', 'produce', 4],
    ['lettuce', 'Lettuce', 'produce', 6],
    ['cucumber', 'Cucumber', 'produce', 7],
    ['zucchini', 'Zucchini', 'produce', 7],
    ['mushroom', 'Mushrooms', 'produce', 5],
    ['coriander', 'Coriander', 'produce', 5],
    ['parsley', 'Parsley', 'produce', 6],
    ['basil', 'Basil', 'produce', 5],
    ['mint', 'Mint', 'produce', 6],
    ['corn', 'Corn', 'produce', 5],
    ['pumpkin', 'Pumpkin', 'produce', 30],

    // meat
    ['chicken_breast', 'Chicken breast', 'meat', 3],
    ['chicken_thigh', 'Chicken thigh', 'meat', 3],
    ['chicken_whole', 'Whole chicken', 'meat', 3],
    ['beef_mince', 'Beef mince', 'meat', 2],
    ['pork_mince', 'Pork mince', 'meat', 2],
    ['beef_steak', 'Beef steak', 'meat', 4],
    ['lamb_cutlet', 'Lamb cutlets', 'meat', 3],
    ['snags', 'Snags', 'meat', 4],
    ['bacon', 'Bacon', 'meat', 7],
    ['prawns', 'Prawns', 'meat', 2],
    ['salmon', 'Salmon', 'meat', 2],
    ['barramundi', 'Barramundi', 'meat', 2],
    ['ham_sliced', 'Sliced ham', 'meat', 7],

    // dairy
    ['milk', 'Milk', 'dairy', 7],
    ['butter', 'Butter', 'dairy', 30],
    ['eggs', 'Eggs', 'dairy', 21],
    ['cheddar', 'Cheddar', 'dairy', 21],
    ['parmesan', 'Parmesan', 'dairy', 30],
    ['feta', 'Feta', 'dairy', 14],
    ['yoghurt', 'Greek yoghurt', 'dairy', 14],
    ['cream', 'Thickened cream', 'dairy', 10],
    ['mozzarella', 'Mozzarella', 'dairy', 10],
    ['haloumi', 'Haloumi', 'dairy', 14],

    // pantry
    ['pasta', 'Pasta', 'pantry', 365],
    ['spaghetti', 'Spaghetti', 'pantry', 365],
    ['rice_jasmine', 'Jasmine rice', 'pantry', 365],
    ['rice_basmati', 'Basmati rice', 'pantry', 365],
    ['bread', 'Bread', 'pantry', 5],
    ['wrap', 'Wraps', 'pantry', 14],
    ['olive_oil', 'Olive oil', 'pantry', 365],
    ['vegetable_oil', 'Vegetable oil', 'pantry', 365],
    ['soy_sauce', 'Soy sauce', 'pantry', 365],
    ['fish_sauce', 'Fish sauce', 'pantry', 365],
    ['oyster_sauce', 'Oyster sauce', 'pantry', 365],
    ['vinegar_balsamic', 'Balsamic vinegar', 'pantry', 365],
    ['salt', 'Sea salt', 'pantry', 730],
    ['pepper', 'Black pepper', 'pantry', 365],
    ['sugar', 'Sugar', 'pantry', 365],
    ['flour', 'Plain flour', 'pantry', 180],
    ['tinned_tomato', 'Tinned tomatoes', 'pantry', 730],
    ['tinned_chickpea', 'Tinned chickpeas', 'pantry', 730],
    ['tinned_bean', 'Tinned beans', 'pantry', 730],
    ['tinned_tuna', 'Tinned tuna', 'pantry', 730],
    ['coconut_milk', 'Coconut milk', 'pantry', 365],
    ['curry_paste_red', 'Red curry paste', 'pantry', 180],
    ['curry_paste_green', 'Green curry paste', 'pantry', 180],
    ['stock_chicken', 'Chicken stock', 'pantry', 365],
    ['stock_veg', 'Vegetable stock', 'pantry', 365],
    ['honey', 'Honey', 'pantry', 730],
    ['peanut_butter', 'Peanut butter', 'pantry', 180],
    ['vegemite', 'Vegemite', 'pantry', 730],
    ['weetbix', 'Weet-Bix', 'pantry', 180],
    ['oats', 'Rolled oats', 'pantry', 180],
    ['muesli', 'Muesli', 'pantry', 90],
    ['cumin', 'Ground cumin', 'pantry', 365],
    ['paprika', 'Smoked paprika', 'pantry', 365],
    ['chilli_powder', 'Chilli powder', 'pantry', 365],
    ['cinnamon', 'Cinnamon', 'pantry', 365],
    ['curry_powder', 'Curry powder', 'pantry', 365],
    ['chickpea_dry', 'Dried chickpeas', 'pantry', 365],
    ['lentil_red', 'Red lentils', 'pantry', 365],
    ['breadcrumbs', 'Breadcrumbs', 'pantry', 120],
    ['tortilla', 'Tortillas', 'pantry', 14],

    // frozen
    ['peas_frozen', 'Frozen peas', 'frozen', 180],
    ['berries_frozen', 'Frozen berries', 'frozen', 180],
    ['pastry_puff', 'Puff pastry', 'frozen', 120],
    ['ice_cream', 'Ice cream', 'frozen', 90],

    // other
    ['coffee', 'Coffee beans', 'other', 60],
    ['tea', 'Tea bags', 'other', 365],
    ['wine_white', 'White wine', 'other', 30],
  ];

  const ingredients = ING.map(([id, display, section, shelf]) => ({
    id, display, section, shelf,
  }));
  const byId = Object.fromEntries(ingredients.map((i) => [i.id, i]));

  // aliases for parser
  const aliases = {
    'chicken breast': 'chicken_breast', 'chicken breasts': 'chicken_breast',
    'chook': 'chicken_whole', 'chook breast': 'chicken_breast',
    'chicken thigh': 'chicken_thigh', 'chicken thighs': 'chicken_thigh',
    'mince': 'beef_mince', 'beef mince': 'beef_mince',
    'steak': 'beef_steak', 'lamb': 'lamb_cutlet', 'snags': 'snags', 'sausages': 'snags',
    'bacon': 'bacon', 'prawns': 'prawns', 'salmon': 'salmon',
    'milk': 'milk', 'butter': 'butter', 'eggs': 'eggs', 'egg': 'eggs',
    'cheese': 'cheddar', 'cheddar': 'cheddar', 'parmesan': 'parmesan',
    'yoghurt': 'yoghurt', 'yogurt': 'yoghurt', 'feta': 'feta', 'haloumi': 'haloumi',
    'banana': 'banana', 'bananas': 'banana',
    'apple': 'apple', 'apples': 'apple',
    'lemon': 'lemon', 'lemons': 'lemon', 'lime': 'lime', 'limes': 'lime',
    'avocado': 'avocado', 'avo': 'avocado', 'avos': 'avocado',
    'tomato': 'tomato', 'tomatoes': 'tomato', 'cherry tomatoes': 'cherry_tomato',
    'roma tomatoes': 'roma_tomato', 'roma': 'roma_tomato',
    'onion': 'onion_brown', 'onions': 'onion_brown', 'brown onion': 'onion_brown',
    'red onion': 'onion_red', 'spring onion': 'spring_onion', 'shallots': 'spring_onion',
    'garlic': 'garlic', 'ginger': 'ginger',
    'capsicum': 'capsicum_red', 'red capsicum': 'capsicum_red', 'green capsicum': 'capsicum_green',
    'chilli': 'chilli', 'chillies': 'chilli',
    'carrot': 'carrot', 'carrots': 'carrot',
    'potato': 'potato', 'potatoes': 'potato', 'spuds': 'potato',
    'sweet potato': 'sweet_potato', 'kumara': 'sweet_potato',
    'broccoli': 'broccoli', 'cauliflower': 'cauliflower',
    'spinach': 'spinach', 'baby spinach': 'spinach',
    'rocket': 'rocket', 'lettuce': 'lettuce',
    'cucumber': 'cucumber', 'zucchini': 'zucchini',
    'mushroom': 'mushroom', 'mushrooms': 'mushroom', 'mushies': 'mushroom',
    'coriander': 'coriander', 'parsley': 'parsley',
    'basil': 'basil', 'mint': 'mint',
    'corn': 'corn', 'pumpkin': 'pumpkin',
    'pasta': 'pasta', 'spaghetti': 'spaghetti',
    'rice': 'rice_jasmine', 'jasmine rice': 'rice_jasmine', 'basmati': 'rice_basmati',
    'bread': 'bread', 'wraps': 'wrap', 'wrap': 'wrap', 'tortillas': 'tortilla',
    'olive oil': 'olive_oil', 'oil': 'olive_oil',
    'soy sauce': 'soy_sauce', 'fish sauce': 'fish_sauce', 'oyster sauce': 'oyster_sauce',
    'balsamic': 'vinegar_balsamic', 'balsamic vinegar': 'vinegar_balsamic',
    'salt': 'salt', 'pepper': 'pepper', 'sugar': 'sugar', 'flour': 'flour',
    'tinned tomatoes': 'tinned_tomato', 'tin tomatoes': 'tinned_tomato', 'canned tomatoes': 'tinned_tomato',
    'chickpeas': 'tinned_chickpea', 'beans': 'tinned_bean', 'tuna': 'tinned_tuna',
    'coconut milk': 'coconut_milk',
    'red curry paste': 'curry_paste_red', 'green curry paste': 'curry_paste_green',
    'chicken stock': 'stock_chicken', 'stock': 'stock_chicken', 'veg stock': 'stock_veg',
    'honey': 'honey', 'peanut butter': 'peanut_butter', 'pb': 'peanut_butter',
    'vegemite': 'vegemite', 'weet-bix': 'weetbix', 'weetbix': 'weetbix',
    'oats': 'oats', 'rolled oats': 'oats', 'muesli': 'muesli',
    'cumin': 'cumin', 'paprika': 'paprika', 'chilli powder': 'chilli_powder',
    'cinnamon': 'cinnamon', 'curry powder': 'curry_powder',
    'red lentils': 'lentil_red', 'lentils': 'lentil_red',
    'breadcrumbs': 'breadcrumbs',
    'peas': 'peas_frozen', 'frozen peas': 'peas_frozen',
    'berries': 'berries_frozen', 'frozen berries': 'berries_frozen',
    'puff pastry': 'pastry_puff', 'ice cream': 'ice_cream',
    'coffee': 'coffee', 'tea': 'tea', 'white wine': 'wine_white',
    'cream': 'cream', 'thickened cream': 'cream', 'mozzarella': 'mozzarella',
  };

  // --- Recipes: 52 curated ---
  const R = (title, description, prep, cook, serves, tags, ingredients, steps, palette) => ({
    title, description, prep, cook, serves, tags, ingredients, steps, palette,
  });

  const recipes = [
    R('Spaghetti Bolognese', 'The weeknight classic. Slow-simmered mince, rich tinned tomato, a knob of butter to finish.',
      15, 35, 4, ['comfort','one-pot','family'],
      [{id:'beef_mince',amt:'500 g'},{id:'onion_brown',amt:'1'},{id:'garlic',amt:'3 cloves'},{id:'tinned_tomato',amt:'2 tins'},{id:'spaghetti',amt:'400 g'},{id:'parmesan',amt:'to serve'},{id:'olive_oil',amt:'glug'},{id:'salt',amt:'pinch'}],
      ['Dice onion, mince garlic.','Brown mince in olive oil, 6 min.','Add onion and garlic, cook until soft.','Tip in tinned tomatoes, season, simmer 20 min.','Cook spaghetti to package instructions.','Toss through sauce, top with parmesan.'],
      ['#c2410c','#fde6d4']),

    R('Green Thai Curry', 'Bright, punchy green curry with chicken thigh and coconut milk.',
      10, 20, 4, ['thai','quick','gluten-free'],
      [{id:'chicken_thigh',amt:'600 g'},{id:'curry_paste_green',amt:'3 tbsp'},{id:'coconut_milk',amt:'400 ml'},{id:'fish_sauce',amt:'1 tbsp'},{id:'rice_jasmine',amt:'2 cups'},{id:'basil',amt:'handful'},{id:'lime',amt:'1'},{id:'chilli',amt:'1'}],
      ['Fry curry paste in a splash of oil, 1 min.','Add diced chicken, toss to coat.','Pour in coconut milk, simmer 12 min.','Season with fish sauce and lime.','Serve over jasmine rice, top with basil and chilli.'],
      ['#65a30d','#e4f3cf']),

    R('Chicken Tikka Masala', 'Yoghurt-marinated chicken in a tomato-cream sauce. Better than takeaway.',
      20, 25, 4, ['indian','family'],
      [{id:'chicken_thigh',amt:'700 g'},{id:'yoghurt',amt:'1/2 cup'},{id:'curry_powder',amt:'2 tbsp'},{id:'tinned_tomato',amt:'1 tin'},{id:'cream',amt:'1/2 cup'},{id:'onion_brown',amt:'1'},{id:'garlic',amt:'3 cloves'},{id:'rice_basmati',amt:'2 cups'},{id:'coriander',amt:'handful'}],
      ['Marinate chicken in yoghurt and curry powder, 30 min or overnight.','Sear chicken in hot pan, set aside.','Soften onion and garlic.','Add tomatoes, simmer 10 min, then cream.','Return chicken, simmer 8 min.','Serve over basmati, top with coriander.'],
      ['#dc2626','#fde2e2']),

    R('Haloumi Grain Bowl', 'Crispy haloumi, roast pumpkin, rocket, lemon. Lunch goals.',
      10, 25, 2, ['vegetarian','quick'],
      [{id:'haloumi',amt:'250 g'},{id:'pumpkin',amt:'400 g'},{id:'rocket',amt:'3 handfuls'},{id:'rice_basmati',amt:'1 cup'},{id:'lemon',amt:'1'},{id:'olive_oil',amt:'glug'},{id:'cumin',amt:'1 tsp'}],
      ['Roast pumpkin with oil and cumin, 25 min at 200°C.','Cook rice.','Fry haloumi slices till golden both sides.','Assemble bowl: rice, rocket, pumpkin, haloumi.','Squeeze lemon over the lot.'],
      ['#f59e0b','#fff1d6']),

    R('Sausage Pasta Bake', 'Snags out of their skins, tomato, pasta, a crust of cheese. Feeds a crowd.',
      10, 30, 6, ['family','comfort','batch-friendly'],
      [{id:'snags',amt:'6'},{id:'pasta',amt:'500 g'},{id:'tinned_tomato',amt:'2 tins'},{id:'onion_brown',amt:'1'},{id:'garlic',amt:'3 cloves'},{id:'mozzarella',amt:'200 g'},{id:'basil',amt:'handful'}],
      ['Squeeze snag meat out of skins, brown in pan.','Add diced onion and garlic, soften.','Pour in tomatoes, simmer.','Cook pasta, reserving some water.','Combine, tip into dish, top with mozzarella.','Bake 15 min at 200°C until bubbly.'],
      ['#b45309','#fbead1']),

    R('Sunday Roast Chook', 'Whole chicken, crispy skin, lemon and garlic.',
      10, 75, 4, ['family','sunday'],
      [{id:'chicken_whole',amt:'1.6 kg'},{id:'lemon',amt:'1'},{id:'garlic',amt:'1 head'},{id:'potato',amt:'1 kg'},{id:'olive_oil',amt:'glug'},{id:'salt',amt:'flakes'},{id:'pepper',amt:'to taste'}],
      ['Preheat oven to 200°C.','Pat chook dry, rub with oil and salt.','Stuff cavity with halved lemon and garlic.','Roast on a bed of potatoes, 75 min.','Rest 10 min before carving.'],
      ['#ca8a04','#fef5d4']),

    R('Veggie Fried Rice', 'Leftover rice, a fridge raid, one pan. Dinner in 10.',
      5, 10, 2, ['quick','vegetarian','one-pot'],
      [{id:'rice_jasmine',amt:'2 cups cooked'},{id:'eggs',amt:'2'},{id:'peas_frozen',amt:'1 cup'},{id:'carrot',amt:'1'},{id:'spring_onion',amt:'3'},{id:'soy_sauce',amt:'2 tbsp'},{id:'garlic',amt:'2 cloves'}],
      ['Scramble eggs, set aside.','Fry garlic and diced carrot.','Add peas and cold rice, toss over high heat.','Pour soy sauce down the side of the pan.','Fold in eggs and spring onion.'],
      ['#059669','#d1f0e0']),

    R('Pumpkin & Chickpea Curry', 'Sweet pumpkin, creamy coconut, warming curry powder.',
      10, 25, 4, ['vegetarian','vegan','gluten-free'],
      [{id:'pumpkin',amt:'600 g'},{id:'tinned_chickpea',amt:'1 tin'},{id:'coconut_milk',amt:'400 ml'},{id:'curry_powder',amt:'2 tbsp'},{id:'onion_brown',amt:'1'},{id:'spinach',amt:'2 handfuls'},{id:'rice_basmati',amt:'2 cups'}],
      ['Soften onion with curry powder.','Add diced pumpkin, toss to coat.','Pour in coconut milk, simmer 20 min.','Add chickpeas and spinach for last 3 min.','Serve over basmati.'],
      ['#ea580c','#fde6d0']),

    R('Lemon Chicken & Rice', 'One-pan, lemon-bright, weeknight winner.',
      5, 30, 4, ['one-pot','quick','family'],
      [{id:'chicken_thigh',amt:'600 g'},{id:'rice_basmati',amt:'1.5 cups'},{id:'stock_chicken',amt:'3 cups'},{id:'lemon',amt:'1'},{id:'garlic',amt:'4 cloves'},{id:'parsley',amt:'handful'},{id:'olive_oil',amt:'glug'}],
      ['Sear chicken in oil, skin-side down.','Remove, add garlic and rice, toast 1 min.','Pour in stock and lemon juice.','Return chicken, cover, simmer 22 min.','Rest 5 min, scatter parsley.'],
      ['#eab308','#fcf0bf']),

    R('BBQ Snag Sanga', 'Bread, snag, grilled onions, sauce. A national treasure.',
      5, 15, 4, ['bbq','quick'],
      [{id:'snags',amt:'8'},{id:'bread',amt:'8 slices'},{id:'onion_brown',amt:'2'},{id:'butter',amt:'knob'}],
      ['Fire up the BBQ.','Slice onions, fry in butter until golden.','Grill snags, turning often.','Butter bread, fold around snag and onions.'],
      ['#a16207','#f8e5c5']),

    R('Prawn Pad Thai', 'Rice noodles, prawns, peanuts, lime. Takeaway at home.',
      15, 10, 2, ['thai','quick'],
      [{id:'prawns',amt:'300 g'},{id:'eggs',amt:'2'},{id:'spring_onion',amt:'3'},{id:'peanut_butter',amt:'1 tbsp'},{id:'fish_sauce',amt:'1 tbsp'},{id:'lime',amt:'1'},{id:'chilli',amt:'1'}],
      ['Mix fish sauce, peanut butter, lime for sauce.','Fry prawns 2 min, remove.','Scramble eggs in pan.','Toss cooked rice noodles with sauce (use spaghetti in a pinch).','Return prawns, top with spring onion and chilli.'],
      ['#d97706','#fdead1']),

    R('Smashed Avo on Toast', 'The brunch standard. Sourdough, avo, feta, lemon, chilli flakes.',
      5, 3, 2, ['breakfast','quick','vegetarian'],
      [{id:'avocado',amt:'1'},{id:'bread',amt:'2 slices'},{id:'feta',amt:'40 g'},{id:'lemon',amt:'1/2'},{id:'chilli_powder',amt:'pinch'},{id:'olive_oil',amt:'drizzle'}],
      ['Toast bread.','Mash avo with lemon and salt.','Pile on toast, crumble feta over.','Drizzle oil, chilli flakes.'],
      ['#16a34a','#d9f0d3']),

    R('Beef Tacos', 'Soft tortillas, spiced mince, avo, lime.',
      10, 15, 4, ['mexican','family','quick'],
      [{id:'beef_mince',amt:'500 g'},{id:'tortilla',amt:'8'},{id:'avocado',amt:'1'},{id:'tomato',amt:'2'},{id:'lime',amt:'1'},{id:'cumin',amt:'1 tsp'},{id:'paprika',amt:'1 tsp'},{id:'coriander',amt:'handful'}],
      ['Brown mince with cumin and paprika.','Dice tomato and avo.','Warm tortillas.','Assemble: mince, toppings, coriander, lime.'],
      ['#ea580c','#fcddbf']),

    R('Zucchini Slice', 'The lunchbox legend. Eggs, zucchini, bacon, a bit of cheese.',
      10, 35, 6, ['family','batch-friendly','vegetarian'],
      [{id:'zucchini',amt:'3'},{id:'eggs',amt:'5'},{id:'bacon',amt:'4 rashers'},{id:'cheddar',amt:'100 g'},{id:'flour',amt:'1 cup'},{id:'onion_brown',amt:'1'}],
      ['Grate zucchini, squeeze out moisture.','Mix with beaten eggs, flour, diced bacon, onion, cheese.','Pour into lined tin.','Bake 35 min at 180°C until set and golden.'],
      ['#84cc16','#ecf7d1']),

    R('Chicken Caesar Salad', 'Crisp lettuce, smoky bacon, parmesan, a punchy dressing.',
      15, 15, 4, ['salad','family'],
      [{id:'chicken_breast',amt:'400 g'},{id:'lettuce',amt:'1'},{id:'bacon',amt:'4 rashers'},{id:'parmesan',amt:'50 g'},{id:'bread',amt:'2 slices'},{id:'eggs',amt:'2'}],
      ['Grill chicken, slice.','Fry bacon until crisp, tear.','Toast bread, cube for croutons.','Boil eggs 6 min, halve.','Toss leaves with dressing, top with all.'],
      ['#4d7c0f','#e2ecc7']),

    R('Tuna Pasta', 'Pantry-raid dinner. Spaghetti, tuna, lemon, chilli.',
      2, 12, 2, ['quick','pantry'],
      [{id:'spaghetti',amt:'200 g'},{id:'tinned_tuna',amt:'1 tin'},{id:'garlic',amt:'2 cloves'},{id:'chilli',amt:'1'},{id:'lemon',amt:'1/2'},{id:'parsley',amt:'handful'},{id:'olive_oil',amt:'glug'}],
      ['Cook pasta.','Warm oil with garlic and chilli.','Flake in tuna, lemon zest.','Toss with pasta and parsley.'],
      ['#0891b2','#cfecf3']),

    R('Red Lentil Dahl', 'The humble hero. Creamy, spiced, cheap.',
      5, 30, 4, ['vegetarian','vegan','gluten-free','batch-friendly'],
      [{id:'lentil_red',amt:'1.5 cups'},{id:'onion_brown',amt:'1'},{id:'garlic',amt:'3 cloves'},{id:'ginger',amt:'thumb'},{id:'tinned_tomato',amt:'1 tin'},{id:'coconut_milk',amt:'200 ml'},{id:'curry_powder',amt:'2 tbsp'},{id:'rice_basmati',amt:'2 cups'}],
      ['Soften onion, garlic, ginger.','Add spices, toast 1 min.','Tip in lentils, tomato, coconut milk, 3 cups water.','Simmer 25 min until thick.','Serve over rice.'],
      ['#b45309','#f6e4ce']),

    R('Mushroom Risotto', 'Slow-stirred, silky, generous with parmesan.',
      10, 30, 4, ['vegetarian','comfort'],
      [{id:'mushroom',amt:'400 g'},{id:'rice_jasmine',amt:'1.5 cups'},{id:'stock_veg',amt:'1 L'},{id:'onion_brown',amt:'1'},{id:'garlic',amt:'2 cloves'},{id:'wine_white',amt:'1/2 cup'},{id:'parmesan',amt:'50 g'},{id:'butter',amt:'knob'}],
      ['Soften onion and garlic in butter.','Add rice, toast 2 min.','Splash in wine, stir till absorbed.','Add stock a ladle at a time, stirring, 20 min.','Fold in fried mushrooms and parmesan.'],
      ['#78716c','#e8e4df']),

    R('Fish Tacos', 'Flaky barramundi, cabbage slaw, lime crema.',
      15, 10, 4, ['mexican','quick','seafood'],
      [{id:'barramundi',amt:'600 g'},{id:'tortilla',amt:'8'},{id:'lettuce',amt:'1/4'},{id:'yoghurt',amt:'1/2 cup'},{id:'lime',amt:'2'},{id:'coriander',amt:'handful'},{id:'paprika',amt:'1 tsp'}],
      ['Season fish with paprika, pan-fry 3 min each side.','Shred lettuce.','Stir yoghurt with lime juice for crema.','Flake fish, fill warm tortillas, top with slaw and crema.'],
      ['#0284c7','#d2eaf6']),

    R('Shakshuka', 'Eggs poached in a spiced tomato sauce. Weekend brunch.',
      5, 20, 2, ['breakfast','vegetarian'],
      [{id:'eggs',amt:'4'},{id:'tinned_tomato',amt:'1 tin'},{id:'capsicum_red',amt:'1'},{id:'onion_brown',amt:'1'},{id:'garlic',amt:'2 cloves'},{id:'paprika',amt:'1 tsp'},{id:'feta',amt:'50 g'},{id:'bread',amt:'2 slices'}],
      ['Soften onion, capsicum, garlic.','Add paprika, then tomatoes, simmer 10 min.','Make wells, crack in eggs.','Cover, cook 5 min till whites set.','Crumble feta, serve with bread.'],
      ['#dc2626','#fbd7d7']),

    R('Pesto Pasta', 'Fresh basil, parmesan, garlic. Fifteen-minute dinner.',
      10, 10, 4, ['quick','vegetarian'],
      [{id:'pasta',amt:'400 g'},{id:'basil',amt:'2 big handfuls'},{id:'parmesan',amt:'60 g'},{id:'garlic',amt:'2 cloves'},{id:'olive_oil',amt:'1/3 cup'},{id:'lemon',amt:'1/2'}],
      ['Blitz basil, garlic, parmesan, oil, lemon.','Cook pasta, reserve splash of water.','Toss pasta with pesto.'],
      ['#16a34a','#daf0d3']),

    R('Chicken Schnitty', 'Pub classic. Crunchy crumb, squeeze of lemon.',
      15, 10, 4, ['family','comfort'],
      [{id:'chicken_breast',amt:'4'},{id:'breadcrumbs',amt:'2 cups'},{id:'eggs',amt:'2'},{id:'flour',amt:'1/2 cup'},{id:'lemon',amt:'1'},{id:'butter',amt:'knob'}],
      ['Butterfly and bash chicken thin.','Flour, egg, crumb.','Shallow-fry in butter, 4 min each side.','Serve with lemon wedges.'],
      ['#d97706','#fbe7c5']),

    R('Sweet Potato Soup', 'Velvety, warming, crowd-pleasing.',
      10, 25, 4, ['vegetarian','vegan','gluten-free','batch-friendly'],
      [{id:'sweet_potato',amt:'800 g'},{id:'onion_brown',amt:'1'},{id:'garlic',amt:'2 cloves'},{id:'stock_veg',amt:'1 L'},{id:'cumin',amt:'1 tsp'},{id:'coconut_milk',amt:'200 ml'}],
      ['Soften onion and garlic.','Add cubed sweet potato and cumin.','Pour in stock, simmer 20 min.','Blitz with coconut milk until silky.'],
      ['#c2410c','#fde6d0']),

    R('Prawn Linguine', 'Garlic, chilli, white wine, parsley.',
      5, 15, 2, ['quick','seafood'],
      [{id:'prawns',amt:'300 g'},{id:'spaghetti',amt:'200 g'},{id:'garlic',amt:'4 cloves'},{id:'chilli',amt:'1'},{id:'wine_white',amt:'1/2 cup'},{id:'parsley',amt:'handful'},{id:'olive_oil',amt:'glug'}],
      ['Cook pasta.','Sizzle garlic and chilli in oil.','Add prawns, cook 2 min, deglaze with wine.','Toss with pasta, parsley, lemon.'],
      ['#ef4444','#fbd7d7']),

    R('Moroccan Lamb', 'Slow-spiced lamb with chickpeas, apricots, couscous.',
      15, 90, 6, ['slow','family'],
      [{id:'lamb_cutlet',amt:'1 kg'},{id:'tinned_chickpea',amt:'1 tin'},{id:'tinned_tomato',amt:'1 tin'},{id:'onion_brown',amt:'2'},{id:'cumin',amt:'2 tsp'},{id:'cinnamon',amt:'1 tsp'},{id:'stock_chicken',amt:'500 ml'},{id:'coriander',amt:'handful'}],
      ['Brown lamb in batches.','Soften onions with spices.','Return lamb, add tomato, chickpeas, stock.','Simmer 90 min, lid off last 20.','Scatter coriander.'],
      ['#b45309','#f4e4cd']),

    R('Breakfast Frittata', 'Sunday clean-out the fridge eggs.',
      5, 20, 4, ['breakfast','vegetarian','batch-friendly'],
      [{id:'eggs',amt:'8'},{id:'potato',amt:'2'},{id:'spinach',amt:'2 handfuls'},{id:'feta',amt:'80 g'},{id:'onion_brown',amt:'1'},{id:'olive_oil',amt:'glug'}],
      ['Par-boil diced potato.','Fry onion and potato until golden.','Add spinach to wilt.','Pour over beaten eggs, dot with feta.','Finish under grill 5 min till puffed.'],
      ['#ca8a04','#fcf0bf']),

    R('Steak & Chips', 'Hot pan, butter, a pile of chips. No frills.',
      10, 20, 2, ['family','comfort'],
      [{id:'beef_steak',amt:'2'},{id:'potato',amt:'600 g'},{id:'butter',amt:'knob'},{id:'garlic',amt:'2 cloves'},{id:'salt',amt:'flakes'}],
      ['Roast chip-cut potatoes 25 min.','Pat steaks dry, season.','Blazing hot pan, 3 min a side, butter basted.','Rest 5 min. Serve with chips.'],
      ['#7c2d12','#e8cfbf']),

    R('Veggie Wrap', 'Lunch for humans who hate the sad desk salad.',
      8, 0, 1, ['vegetarian','quick','no-cook'],
      [{id:'wrap',amt:'1'},{id:'haloumi',amt:'60 g'},{id:'avocado',amt:'1/2'},{id:'cucumber',amt:'1/4'},{id:'rocket',amt:'handful'},{id:'feta',amt:'30 g'}],
      ['Grill haloumi slices.','Warm wrap.','Layer with avo, haloumi, cucumber, rocket, feta.','Roll tight, slice on the bias.'],
      ['#65a30d','#e5f2cf']),

    R('Chilli Con Carne', 'Smoky, spicy, crowd-feeding.',
      10, 45, 6, ['mexican','family','batch-friendly'],
      [{id:'beef_mince',amt:'700 g'},{id:'tinned_bean',amt:'2 tins'},{id:'tinned_tomato',amt:'2 tins'},{id:'onion_brown',amt:'1'},{id:'capsicum_red',amt:'1'},{id:'cumin',amt:'1 tsp'},{id:'paprika',amt:'1 tbsp'},{id:'chilli_powder',amt:'1 tsp'}],
      ['Brown mince with spices.','Add diced onion and capsicum.','Tip in tomatoes and beans.','Simmer 40 min.','Serve with rice or corn chips.'],
      ['#991b1b','#f5d5d5']),

    R('Banana Bread', 'Speckled bananas, brown butter, the kindest loaf.',
      10, 55, 8, ['baking','snack'],
      [{id:'banana',amt:'3'},{id:'flour',amt:'2 cups'},{id:'sugar',amt:'3/4 cup'},{id:'butter',amt:'100 g'},{id:'eggs',amt:'2'},{id:'cinnamon',amt:'1 tsp'}],
      ['Mash bananas.','Cream butter and sugar, add eggs.','Fold in bananas, flour, cinnamon.','Bake 55 min at 170°C.','Cool in tin 15 min.'],
      ['#f59e0b','#fff1c9']),

    R('Poached Eggs', 'Vinegar, simmer, spoon, done. Eggs-ellence.',
      2, 4, 1, ['breakfast','quick'],
      [{id:'eggs',amt:'2'},{id:'bread',amt:'2 slices'},{id:'butter',amt:'knob'}],
      ['Simmer water with a splash of vinegar.','Swirl, slip in egg, 3 min.','Lift, rest on tea towel.','Pile on buttered toast.'],
      ['#ca8a04','#fcf0bf']),

    R('Greek Salad', 'Tomato, cucumber, olives, feta, oregano. Nothing hiding.',
      10, 0, 4, ['vegetarian','salad','no-cook','quick'],
      [{id:'tomato',amt:'4'},{id:'cucumber',amt:'1'},{id:'onion_red',amt:'1/2'},{id:'feta',amt:'200 g'},{id:'olive_oil',amt:'glug'},{id:'lemon',amt:'1'}],
      ['Chunk tomato, cucumber, red onion.','Toss with oil and lemon.','Top with feta slab.','Crack of pepper.'],
      ['#059669','#d0eedc']),

    R('Hummus & Flatbread', 'Creamy chickpea dip. Snack-dinner energy.',
      10, 0, 4, ['vegetarian','vegan','no-cook'],
      [{id:'tinned_chickpea',amt:'1 tin'},{id:'garlic',amt:'2 cloves'},{id:'lemon',amt:'1'},{id:'olive_oil',amt:'1/3 cup'},{id:'cumin',amt:'1 tsp'},{id:'wrap',amt:'4'}],
      ['Blitz chickpeas, garlic, lemon, cumin.','Stream in oil till silky.','Warm wraps, tear, dip.'],
      ['#a16207','#f5e5c5']),

    R('Carbonara', 'Eggs, parmesan, bacon, pepper. No cream. Fight me.',
      5, 15, 2, ['quick','italian','comfort'],
      [{id:'spaghetti',amt:'200 g'},{id:'bacon',amt:'100 g'},{id:'eggs',amt:'2'},{id:'parmesan',amt:'50 g'},{id:'pepper',amt:'lots'}],
      ['Crisp bacon.','Cook spaghetti, reserve water.','Whisk eggs, parmesan, pepper.','Off heat, toss pasta with egg mix, loosen with water.','Fold in bacon.'],
      ['#ca8a04','#fcf0bf']),

    R('Salmon Teriyaki', 'Sticky, glossy, rice underneath.',
      5, 12, 2, ['seafood','japanese','quick'],
      [{id:'salmon',amt:'2 fillets'},{id:'soy_sauce',amt:'3 tbsp'},{id:'honey',amt:'2 tbsp'},{id:'ginger',amt:'thumb'},{id:'rice_jasmine',amt:'1 cup'},{id:'spring_onion',amt:'2'}],
      ['Sear salmon skin-side down.','Mix soy, honey, grated ginger.','Add sauce, reduce until sticky.','Serve over rice with spring onion.'],
      ['#be185d','#f4d0de']),

    R('Potato Salad', 'BBQ side dish of the gods.',
      10, 15, 6, ['salad','bbq','vegetarian'],
      [{id:'potato',amt:'1 kg'},{id:'eggs',amt:'4'},{id:'yoghurt',amt:'1/2 cup'},{id:'spring_onion',amt:'3'},{id:'parsley',amt:'handful'}],
      ['Boil potatoes till tender.','Boil eggs 8 min, cool, chop.','Toss warm potato with yoghurt, eggs, spring onion.','Season well, scatter parsley.'],
      ['#facc15','#fbf3c2']),

    R('Minestrone', 'Vegetables, beans, pasta. A ladle of summer in winter.',
      15, 30, 6, ['vegetarian','batch-friendly','soup'],
      [{id:'tinned_bean',amt:'1 tin'},{id:'tinned_tomato',amt:'1 tin'},{id:'carrot',amt:'2'},{id:'zucchini',amt:'1'},{id:'onion_brown',amt:'1'},{id:'pasta',amt:'1 cup'},{id:'stock_veg',amt:'1 L'},{id:'parmesan',amt:'to serve'}],
      ['Dice vegetables.','Soften onion, carrot.','Add tomato, beans, stock, simmer 15 min.','Add pasta, cook 8 min.','Top with parmesan.'],
      ['#15803d','#d5ecd6']),

    R('Chicken Noodle Soup', 'Broth for the soul. Sick day cure.',
      10, 25, 4, ['soup','comfort','family'],
      [{id:'chicken_thigh',amt:'400 g'},{id:'carrot',amt:'2'},{id:'stock_chicken',amt:'1.5 L'},{id:'spring_onion',amt:'3'},{id:'spaghetti',amt:'150 g'},{id:'ginger',amt:'thumb'}],
      ['Poach chicken in stock with ginger, 20 min.','Shred.','Cook noodles in broth.','Return chicken, add carrot and spring onion.','Season well.'],
      ['#eab308','#fcf0bf']),

    R('Pork Larb', 'Thai mince salad. Herby, punchy, easy.',
      10, 10, 4, ['thai','quick','gluten-free'],
      [{id:'pork_mince',amt:'500 g'},{id:'fish_sauce',amt:'2 tbsp'},{id:'lime',amt:'2'},{id:'spring_onion',amt:'3'},{id:'mint',amt:'handful'},{id:'coriander',amt:'handful'},{id:'chilli',amt:'1'},{id:'lettuce',amt:'leaves to serve'}],
      ['Brown mince in dry pan till crisp.','Off heat, toss with fish sauce, lime, herbs, chilli.','Spoon into lettuce cups.'],
      ['#84cc16','#ecf6d2']),

    R('Eggplant Parma', 'The vego pub hero. Crumbed, tomato, bubbly cheese.',
      20, 30, 4, ['vegetarian','comfort'],
      [{id:'zucchini',amt:'1'},{id:'eggs',amt:'2'},{id:'flour',amt:'1/2 cup'},{id:'breadcrumbs',amt:'2 cups'},{id:'tinned_tomato',amt:'1 tin'},{id:'mozzarella',amt:'150 g'},{id:'basil',amt:'handful'}],
      ['Slice zucchini lengthways.','Flour, egg, crumb, fry golden.','Layer in dish with tomato and mozzarella.','Bake 25 min at 200°C.','Basil to finish.'],
      ['#7c3aed','#e4d8f3']),

    R('Breakfast Burrito', 'Eggs, beans, cheese, all rolled up.',
      10, 10, 2, ['breakfast','quick'],
      [{id:'eggs',amt:'4'},{id:'tinned_bean',amt:'1 tin'},{id:'cheddar',amt:'60 g'},{id:'tortilla',amt:'2 large'},{id:'avocado',amt:'1'},{id:'coriander',amt:'handful'}],
      ['Scramble eggs.','Warm beans, mash lightly.','Pile onto warm tortillas with cheese, avo.','Roll tight, sear seam-side down.'],
      ['#ea580c','#fddcc5']),

    R('Stir-Fry Beef', 'Fridge-emptying weeknight. Hot wok, fast hands.',
      10, 10, 4, ['quick','one-pot','asian'],
      [{id:'beef_steak',amt:'500 g'},{id:'broccoli',amt:'1 head'},{id:'capsicum_red',amt:'1'},{id:'oyster_sauce',amt:'3 tbsp'},{id:'garlic',amt:'3 cloves'},{id:'ginger',amt:'thumb'},{id:'rice_jasmine',amt:'2 cups'}],
      ['Slice beef thin, marinate in soy and ginger.','Blast in hot wok, 1 min, remove.','Stir-fry veg, add garlic.','Return beef, splash in oyster sauce.','Over rice.'],
      ['#92400e','#f3dcc4']),

    R('Greek Lamb Souva', 'Skewers, tzatziki, warm bread. Backyard Friday.',
      20, 10, 4, ['bbq','family'],
      [{id:'lamb_cutlet',amt:'600 g'},{id:'yoghurt',amt:'1 cup'},{id:'cucumber',amt:'1/2'},{id:'garlic',amt:'2 cloves'},{id:'mint',amt:'handful'},{id:'lemon',amt:'1'},{id:'wrap',amt:'4'}],
      ['Cube lamb, skewer, marinate in oil and lemon.','Grate cucumber into yoghurt with garlic and mint.','Grill skewers 8 min.','Serve in warm flatbread with tzatziki.'],
      ['#dc2626','#fbd7d7']),

    R('Fried Egg Sandwich', 'Yolk, butter, sauce of your choosing.',
      3, 5, 1, ['breakfast','quick','cheap'],
      [{id:'eggs',amt:'2'},{id:'bread',amt:'2 slices'},{id:'butter',amt:'knob'},{id:'vegemite',amt:'scrape'}],
      ['Butter bread, scrape one side with vegemite.','Fry eggs to your liking.','Sandwich. Mess is expected.'],
      ['#7f1d1d','#e8cfcf']),

    R('Mac & Cheese', 'Béchamel, cheddar, pasta, bubbly top. Comfort.',
      10, 30, 6, ['family','comfort','vegetarian'],
      [{id:'pasta',amt:'500 g'},{id:'milk',amt:'750 ml'},{id:'butter',amt:'60 g'},{id:'flour',amt:'60 g'},{id:'cheddar',amt:'250 g'},{id:'breadcrumbs',amt:'1/2 cup'}],
      ['Cook pasta.','Make béchamel: melt butter, whisk in flour, milk.','Off heat, melt in cheese.','Fold in pasta.','Top with crumbs, bake 15 min at 200°C.'],
      ['#ca8a04','#fcf0bf']),

    R('Lentil Bolognese', 'All the depth of a slow ragù. Zero meat.',
      10, 40, 6, ['vegetarian','vegan','batch-friendly'],
      [{id:'lentil_red',amt:'1.5 cups'},{id:'tinned_tomato',amt:'2 tins'},{id:'carrot',amt:'2'},{id:'onion_brown',amt:'1'},{id:'garlic',amt:'3 cloves'},{id:'spaghetti',amt:'400 g'},{id:'stock_veg',amt:'500 ml'}],
      ['Soften diced carrot, onion, garlic.','Add lentils, stock, tomatoes.','Simmer 35 min till thick.','Toss with cooked spaghetti.'],
      ['#b45309','#f4e1ca']),

    R('Roast Veg Couscous', 'Meal-prep friendly, pretty, bright.',
      10, 30, 4, ['vegetarian','batch-friendly'],
      [{id:'sweet_potato',amt:'500 g'},{id:'capsicum_red',amt:'2'},{id:'zucchini',amt:'1'},{id:'onion_red',amt:'1'},{id:'feta',amt:'100 g'},{id:'lemon',amt:'1'},{id:'olive_oil',amt:'glug'}],
      ['Chop and roast veg 30 min, 200°C.','Make couscous per packet.','Toss veg through couscous with lemon.','Crumble feta on top.'],
      ['#d97706','#fce4c9']),

    R('Chicken Parma', 'Schnitty, napoli, ham, cheese. The classic.',
      15, 20, 4, ['family','comfort','pub'],
      [{id:'chicken_breast',amt:'4'},{id:'breadcrumbs',amt:'2 cups'},{id:'eggs',amt:'2'},{id:'flour',amt:'1/2 cup'},{id:'tinned_tomato',amt:'1 tin'},{id:'ham_sliced',amt:'4 slices'},{id:'mozzarella',amt:'150 g'}],
      ['Crumb and shallow-fry schnitties.','Reduce tomato with garlic, salt.','Top each schnitty with napoli, ham, mozzarella.','Grill till melted.'],
      ['#c2410c','#fbdfc8']),

    R('Overnight Oats', 'Tomorrow-you will thank today-you.',
      5, 0, 1, ['breakfast','no-cook','quick'],
      [{id:'oats',amt:'1/2 cup'},{id:'milk',amt:'1/2 cup'},{id:'yoghurt',amt:'1/3 cup'},{id:'honey',amt:'1 tsp'},{id:'berries_frozen',amt:'1/2 cup'}],
      ['Mix oats, milk, yoghurt, honey in a jar.','Top with berries.','Lid on, fridge overnight.'],
      ['#d97706','#fdeed1']),

    R('Pancakes', 'Stack, butter, syrup. Weekend mandate.',
      5, 15, 4, ['breakfast','family'],
      [{id:'flour',amt:'1.5 cups'},{id:'milk',amt:'1.5 cups'},{id:'eggs',amt:'1'},{id:'butter',amt:'50 g'},{id:'sugar',amt:'2 tbsp'}],
      ['Whisk dry, then wet ingredients.','Rest 10 min.','Cook 2 min a side in buttered pan.','Stack unreasonably high.'],
      ['#facc15','#fbf3c2']),

    R('Fish & Chips', 'Beer batter, crispy chips, fresh lemon.',
      10, 20, 4, ['family','seafood','pub'],
      [{id:'barramundi',amt:'600 g'},{id:'potato',amt:'1 kg'},{id:'flour',amt:'1 cup'},{id:'lemon',amt:'1'},{id:'vegetable_oil',amt:'to fry'}],
      ['Cut chips, twice-fry or oven-bake.','Make batter with flour, beer, salt.','Dip fish, fry 4 min till crisp.','Serve with lemon.'],
      ['#f59e0b','#fef0d0']),

    R('Thai Beef Salad', 'Rare beef, herbs, chilli, lime. Summer dinner.',
      10, 8, 4, ['thai','salad','quick'],
      [{id:'beef_steak',amt:'500 g'},{id:'cucumber',amt:'1'},{id:'cherry_tomato',amt:'200 g'},{id:'mint',amt:'handful'},{id:'coriander',amt:'handful'},{id:'fish_sauce',amt:'2 tbsp'},{id:'lime',amt:'2'},{id:'chilli',amt:'1'}],
      ['Sear steak rare, rest, slice.','Toss veg and herbs with fish sauce, lime, chilli.','Fan beef over the top.'],
      ['#dc2626','#f9d5d5']),
  ];

  // --- Shopping lists ---
  const listSeed = [
    {
      id: 'list-1', name: 'Weekly shop', created: Date.now() - 2 * 86400000, archived: false,
      items: [
        // produce
        { ing: 'banana', bought: true },
        { ing: 'capsicum_red', bought: true },
        { ing: 'broccoli', bought: true },
        { ing: 'spinach', bought: true },
        { ing: 'coriander', bought: true },
        { ing: 'lemon', bought: true },
        { ing: 'garlic', bought: false },
        { ing: 'onion_brown', bought: false },
        // meat
        { ing: 'chicken_thigh', bought: true },
        { ing: 'beef_mince', bought: false },
        // dairy
        { ing: 'milk', bought: true },
        { ing: 'yoghurt', bought: true },
        { ing: 'feta', bought: false },
        // pantry
        { ing: 'pasta', bought: false },
        { ing: 'tinned_tomato', bought: true },
        { custom: 'Tim Tams', section: 'pantry', bought: false },
      ],
    },
    {
      id: 'list-2', name: 'BBQ Saturday', created: Date.now() - 86400000, archived: false,
      items: [
        { ing: 'snags', bought: false },
        { ing: 'bread', bought: false },
        { ing: 'onion_brown', bought: false },
        { ing: 'potato', bought: false },
        { ing: 'beef_steak', bought: false },
        { ing: 'lemon', bought: false },
        { ing: 'wine_white', bought: false },
        { custom: 'Ice', section: 'other', bought: false },
      ],
    },
    {
      id: 'list-3', name: 'Quick top-up', created: Date.now() - 5 * 86400000, archived: true,
      items: [
        { ing: 'milk', bought: true }, { ing: 'bread', bought: true }, { ing: 'eggs', bought: true },
      ],
    },
  ];

  // --- Pantry seed (30 items, mix of expiry states) ---
  const D = 86400000;
  const now = Date.now();
  const pantrySeed = [
    // expiring soon
    { ing: 'chicken_breast', added: now - 1*D, expires: now + 2*D },
    { ing: 'spinach', added: now - 3*D, expires: now + 1*D },
    { ing: 'coriander', added: now - 3*D, expires: now + 2*D },
    { ing: 'mushroom', added: now - 2*D, expires: now + 3*D },
    { ing: 'beef_mince', added: now - 1*D, expires: now + 1*D, low: true },
    // expired (will show red)
    { ing: 'cream', added: now - 12*D, expires: now - 1*D },
    // fresh
    { ing: 'onion_brown', added: now - 2*D, expires: now + 28*D },
    { ing: 'garlic', added: now - 5*D, expires: now + 25*D },
    { ing: 'carrot', added: now - 3*D, expires: now + 18*D },
    { ing: 'capsicum_red', added: now - 2*D, expires: now + 6*D },
    { ing: 'lemon', added: now - 4*D, expires: now + 17*D },
    { ing: 'tomato', added: now - 2*D, expires: now + 4*D },
    { ing: 'potato', added: now - 7*D, expires: now + 23*D, low: true },
    { ing: 'eggs', added: now - 4*D, expires: now + 17*D },
    { ing: 'milk', added: now - 2*D, expires: now + 5*D },
    { ing: 'butter', added: now - 14*D, expires: now + 16*D },
    { ing: 'cheddar', added: now - 8*D, expires: now + 13*D },
    { ing: 'yoghurt', added: now - 3*D, expires: now + 11*D },
    { ing: 'feta', added: now - 6*D, expires: now + 8*D },
    { ing: 'pasta', added: now - 20*D, expires: now + 345*D },
    { ing: 'spaghetti', added: now - 40*D, expires: now + 325*D },
    { ing: 'rice_jasmine', added: now - 60*D, expires: now + 305*D },
    { ing: 'tinned_tomato', added: now - 30*D, expires: now + 700*D },
    { ing: 'tinned_chickpea', added: now - 20*D, expires: now + 710*D },
    { ing: 'coconut_milk', added: now - 20*D, expires: now + 345*D, low: true },
    { ing: 'olive_oil', added: now - 90*D, expires: now + 275*D },
    { ing: 'soy_sauce', added: now - 120*D, expires: now + 245*D },
    { ing: 'curry_paste_green', added: now - 30*D, expires: now + 150*D },
    { ing: 'oats', added: now - 15*D, expires: now + 165*D },
    { ing: 'peas_frozen', added: now - 30*D, expires: now + 150*D },
  ];

  // Group seed
  const group = {
    id: 'g-1',
    name: 'The Wilsons',
    members: [
      { id: 'u-you', name: 'You', color: '#c2410c' },
      { id: 'u-sarah', name: 'Sarah', color: '#0891b2' },
      { id: 'u-mike', name: 'Mike', color: '#65a30d' },
    ],
  };

  const feedSeed = [
    { kind: 'cooked', who: 'u-sarah', recipe: 'Green Thai Curry', t: now - 18 * 3600000 },
    { kind: 'suggest', who: 'u-mike', recipe: 'Chicken Tikka Masala', t: now - 10 * 3600000, date: 'Friday', id: 's-1' },
    { kind: 'comment', who: 'u-sarah', on: 's-1', text: 'yes please, I\'ll pick up naan', t: now - 9 * 3600000 },
    { kind: 'like', who: 'u-you', on: 's-1', t: now - 8 * 3600000 },
    { kind: 'list_add', who: 'u-mike', count: 4, list: 'Weekly shop', t: now - 5 * 3600000 },
    { kind: 'suggest', who: 'u-you', recipe: 'Haloumi Grain Bowl', t: now - 2 * 3600000, date: 'Tomorrow', id: 's-2' },
    { kind: 'comment', who: 'u-mike', on: 's-2', text: 'we\'ve got pumpkin that needs eating, perfect', t: now - 1.5 * 3600000 },
  ];

  return { ingredients, byId, aliases, recipes, listSeed, pantrySeed, group, feedSeed };
})();
